server:
  port: 8081

spring:
  application:
    name: ai-analytics-service

  datasource:
    url: jdbc:postgresql://postgres:5432/habit_db
    username: habit_user
    password: habit_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: ai-analytics-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: akhm.project.ai.dto.HabitReportMessage

  ai:
    openai:
      api-key: ${GEMINI_API_KEY}
      base-url: https://generativelanguage.googleapis.com/v1beta/openai
      chat:
        options:
          model: gemini-3.5-flash-lite
          temperature: 0.7

app:
  kafka:
    topics:
      habit-events: habit-events